/**
 * MCP tools for Iterable campaign operations
 */

import type { IterableClient } from "@iterable/api";
import {
  AbortCampaignParamsSchema,
  ActivateTriggeredCampaignParamsSchema,
  ArchiveCampaignsParamsSchema,
  CancelCampaignParamsSchema,
  CreateCampaignParamsSchema,
  DeactivateTriggeredCampaignParamsSchema,
  GetCampaignMetricsParamsSchema,
  GetCampaignParamsSchema,
  GetCampaignsParamsSchema,
  GetChildCampaignsParamsSchema,
  ScheduleCampaignParamsSchema,
  SendCampaignParamsSchema,
  TriggerCampaignParamsSchema,
} from "@iterable/api";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";

import { createTool } from "../schema-utils.js";

export function createCampaignTools(client: IterableClient): Tool[] {
  return [
    createTool({
      name: "get_campaigns",
      description: "Retrieve campaigns",
      schema: GetCampaignsParamsSchema,
      execute: (params) => client.getCampaigns(params),
    }),

    createTool({
      name: "get_campaign",
      description: "Get detailed information about a specific campaign",
      schema: GetCampaignParamsSchema,
      execute: (params) => client.getCampaign(params),
    }),

    createTool({
      name: "get_campaign_metrics",
      description: "Get campaign performance metrics",
      schema: GetCampaignMetricsParamsSchema,
      execute: (params) => client.getCampaignMetrics(params),
    }),
    createTool({
      name: "create_campaign",
      description:
        "Create a new blast or triggered campaign from an existing template. If listIds are provided, the campaign will be a blast campaign, otherwise it will be a triggered campaign. Blast campaigns will be sent immediately if sendAt is not provided.",
      schema: CreateCampaignParamsSchema,
      execute: (params) => client.createCampaign(params),
    }),
    createTool({
      name: "get_child_campaigns",
      description: "Get child campaigns generated by a recurring campaign",
      schema: GetChildCampaignsParamsSchema,
      execute: (params) => client.getChildCampaigns(params),
    }),
    createTool({
      name: "schedule_campaign",
      description:
        "Schedule an existing campaign to be sent at a specific time",
      schema: ScheduleCampaignParamsSchema,
      execute: (params) => client.scheduleCampaign(params),
    }),
    createTool({
      name: "abort_campaign",
      description: "Abort a campaign that is currently running",
      schema: AbortCampaignParamsSchema,
      execute: (params) => client.abortCampaign(params),
    }),
    createTool({
      name: "cancel_campaign",
      description: "Cancel a scheduled or recurring campaign",
      schema: CancelCampaignParamsSchema,
      execute: (params) => client.cancelCampaign(params),
    }),
    createTool({
      name: "activate_triggered_campaign",
      description:
        "Activate a triggered campaign (requires API triggered campaign activation enabled)",
      schema: ActivateTriggeredCampaignParamsSchema,
      execute: (params) => client.activateTriggeredCampaign(params),
    }),
    createTool({
      name: "deactivate_triggered_campaign",
      description:
        "Deactivate a triggered campaign (requires API triggered campaign deactivation enabled)",
      schema: DeactivateTriggeredCampaignParamsSchema,
      execute: (params) => client.deactivateTriggeredCampaign(params),
    }),
    createTool({
      name: "archive_campaigns",
      description:
        "Archive one or more campaigns. Scheduled/recurring campaigns will be cancelled, running campaigns will be aborted.",
      schema: ArchiveCampaignsParamsSchema,
      execute: (params) => client.archiveCampaigns(params),
    }),
    createTool({
      name: "trigger_campaign",
      description: "Trigger a campaign to send to specified lists",
      schema: TriggerCampaignParamsSchema,
      execute: (params) => client.triggerCampaign(params),
    }),
    createTool({
      name: "send_campaign",
      description: "Send an existing scheduled campaign immediately",
      schema: SendCampaignParamsSchema,
      execute: (params) => client.sendCampaign(params),
    }),
  ];
}
